### ISSUE TITLE
Realizar benchmarking de apps que sejam semelhantes ao objetivo do projeto memória azul

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/MemoriaAzul#15]
Verificar soluções para navegação das coleções dentro do app.

Exemplo de app: whitebook

Relacionado a história #10

**Comment by renatomurasaki** [comment]
![ee2878e1-0dec-484f-a4b4-6dc3476a3db0](https://user-images.githubusercontent.com/1226218/40080740-49bfc58c-5862-11e8-8cb3-a912356b8dcb.jpeg)
