### ISSUE TITLE
Implementar serviço de geração de thumbnail a partir de PDF

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/MemoriaAzul#20]
https://wiki.duraspace.org/display/DSDOC5x/ImageMagick+Media+Filters

**Comment by heitorbarbieri** [comment]
Avaliei o projeto da Apache PDFBox (https://pdfbox.apache.org) que não requer instalação alguma e produz o resultado desejado. Veja exemplo de chamada abaixo:

java -jar pdfbox-app-2.0.9.jar PDFToImage -format jpg -prefix "xdocument" -page 1 "xdocument.pdf"

[pdfbox-app-2.0.9.zip](https://github.com/bireme/MemoriaAzul/files/2068196/pdfbox-app-2.0.9.zip)
(descompactar antes de utilizar o comando acima)

**Comment by heitorbarbieri** [comment]
Processo descrito acima carece de outras bibliotecas. Descompactar arquivo zip abaixo e executar comando abaixo:

java -cp "jai-imageio-jpeg2000-1.3.0.jar:pdfbox-app-2.0.9.jar:jai-imageio-core-1.4.0.jar" org.apache.pdfbox.tools.PDFBox

Como exemplo de chamada:

java -cp "jai-imageio-jpeg2000-1.3.0.jar:pdfbox-app-2.0.9.jar:jai-imageio-core-1.4.0.jar" org.apache.pdfbox.tools.PDFBox PDFToImage -format jpg -prefix saida -page 1 Get-the-Most-Out-of-HttpClient.pdf

Bibliotecas:

[all.zip](https://github.com/bireme/MemoriaAzul/files/2073322/all.zip)
