### ISSUE TITLE
Definir como solucionar o contexto pais na Memória Azul

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/MemoriaAzul#22]
A memória azul tem como público-alvo os profissionais de saúde de um país. Sendo assim, as coleções de documentos serão orientadas às necessidades desse público.

A coleção de Atenção Primária em Saúde para os profissionais do Brasil terá documentos do contexto brasileiro que não se aplicam a outros países. Também poderá conter documentos regionais ou internacionais, como políticas e estratégias da OPAS/OMS, por exemplo, que se aplicam a qualquer nação.

Cenários a avaliar sobre a estrutura de dados:

1) Criar um novo nível de comunidade para separar os países
   O usuário terá que escolher o país antes de navegar nas coleções e sub-coleções.

2) Criar uma estrutura de dados a parte que associe as comunidades e coleções a um país

Cenários a avaliar sobre solução de navegação
1) Criar instâncias de memória azul por pais
   O usuário do Brasil acessará algo do tipo http://xxxx.yyyy.org/brasil/memoria-azul e nessa instância somente haverá comunidades e coleções do Brasil.

2) Criar primeiro nível de comunidade por país
   O usuário acessa sempre o mesmo site/app e seleciona o país de interesse.

3) Configuração do site/app
   O usuário configura o site/app com o país de interesse por meio de um menu.

**Comment by viniciusandrade** [comment]
@wilsonmoura 

Foi adicionado o atributo de país para ser utilizado no nível da comunidade e também foi criado método na API para o retorno da lista de países e a possibilidade de filtro pelo código do país.
Documentado em https://github.com/bireme/fi-admin/wiki/API

**Comment by wilsonmoura** [comment]
Implementado em https://github.com/bireme/memoria-azul-wp-plugin/issues/13
